networks:
  httpd_net:
    ipam:
      config:
        - subnet: 10.101.1.0/24

services:
  httpd_cl:
    container_name: httpd_cl
    hostname: httpd_cl
    image: httpd:2.4
    environment:
      - TZ=America/Santiago
    volumes:
      - ./web-content/:/usr/local/apache2/htdocs/:ro
    networks:
      httpd_net:
        ipv4_address: 10.101.1.10
    ports:
      - "80:80"
